config/routes.rb
DiasporaProjectSite::Application.routes.draw do
  devise_for :users

  get 'switch_locale/:locale' => 'i18n#switch_locale', as: :switch_locale

  constraints subdomain: /^(|www)$/i do
    controller :pages do
      get :about
      get :contributors
      get :formatting
      get :get_involved
      get :other_docs
      get :community_guidelines
      get :tips
      get :tutorials
      scope 'getting_started' do
        get :aspects, action: 'getting_started3'
        get :connecting, action: 'getting_started4'
        get :conversations, action: 'getting_started6'
        get :finishing, action: 'getting_started7'
        get :interface, action: 'getting_started2'
        get :interface_mobile, action: 'getting_started2_mobile'
        get :sharing, action: 'getting_started5'
        get :sign_up, action: 'getting_started1'
      end
    end

    root to: 'pages#index'
  end

  constraints subdomain: /^admin$/i do
    mount RailsAdmin::Engine => '/', as: 'rails_admin'
  end

  constraints subdomain: /^blog$/i do
    get 'feed' => 'blog#feed', :as => :news_feed, :defaults => {:format => :atom}
    resources :blog, path: '/', only: [:index, :show]
  end

  constraints subdomain: /^planet$/i do
    get 'feed' => 'planet#feed', :as => :planet_feed, :defaults => {:format => :atom}
    get '/' => 'planet#index', :as => :planet_index
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/asset.rb
class Asset < ApplicationRecord
  has_attached_file :file, {
    :path => ":rails_root/public/:class/:style/:filename",
    :url => "/:class/:style/:filename",
    :styles => { :large => "800x800>", :medium => "300x300>", :thumb => "100x100>" }
  }
  before_post_process :skip_for_non_images

  do_not_validate_attachment_file_type :file

  validates :file, :attachment_presence => true
  validates_with AttachmentPresenceValidator, :attributes => :file

  private

  def skip_for_non_images
    (file.content_type =~ /^(image|(x-)?application)\/(x-png|pjpeg|jpeg|jpg|png|gif)$/)
  end
end

app/models/blogpost.rb
class Blogpost < ApplicationRecord
  def to_param
    "#{self.id}-#{self.title}".parameterize
  end
end

app/models/contributor.rb
class Contributor < ActiveRecord::Base
  def github_url
    "https://github.com/#{self.github_username}"
  end

  def first_name
    self.name.split(' ').first
  end

  def diaspora_username
   diaspora_id.split('@').first
  end

  def diaspora_url
    username, server = diaspora_id.split('@')
    "http://#{server}/u/#{username}"
  end


  def diaspora_avatar
    "#{diaspora_url}/profile_photo"
  end
end

app/models/donor.rb
class Donor < ActiveRecord::Base
  validate :presence => :stripe_token

  def self.create_with_payment(opts)
    if has_valid_payment?(opts)
      self.create(:stripe_token => opts[:stripeToken], :name => opts[:name], :email => opts[:email])
    end
  end

  def self.has_valid_payment?(opts)
    amount = (opts[:amount].to_s.gsub(/[^0-9\.]/, '').to_f*100).to_i

    Stripe::Charge.create(
        :amount => amount,
        :card => opts[:stripeToken],
        :currency => 'usd',
        :description => nil
    )
  end

end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :recoverable,
         :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def not_found
    raise ActionController::RoutingError.new('Not Found')
  end
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
  respond_to :html, :except => [:feed]
  respond_to :atom, :only => [:feed]

  def show
    @blogpost = Blogpost.find_by_id params[:id]
    not_found unless @blogpost
  end

  def index
    @blogposts = Blogpost.where(:published => true).order(:created_at => :desc)
  end

  def feed
    @blogposts = Blogpost.where(:published => true).order(:created_at => :desc).limit 5
    respond_to do |format|
      format.atom { headers["Content-Type"] = 'application/atom+xml; charset=utf-8'}
    end
  end
end

app/controllers/donors_controller.rb
class DonorsController < ApplicationController

  def update
    if Donor.find_by_stripe_token(params[:donor][:stripe_token]).update_attributes(:email => params[:donor][:email], :name => params[:donor][:name])
      flash[:notice] = "Thanks again for your contribution!  We'll send you an invite in the next 24 hours :)"
    else
      flash[:error] = "There seemed to have been a problem processing your credit card! :("
    end

    redirect_to donate_path
  end
end

app/controllers/i18n_controller.rb
class I18nController < ApplicationController
  def switch_locale
    request.env["HTTP_REFERER"] ||= root_path
    redirect_to :back
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  respond_to :html
end

app/controllers/planet_controller.rb
class PlanetController < ApplicationController
  respond_to :html, :except => [:feed]
  respond_to :atom, :only => [:feed]

  def index
    @entries = Planet::Models::Entry.order(:published_at => :desc)
      .paginate(:page => params[:page], :per_page => 10)
    @subscriptions = Planet::Models::Feed.order(:title => :asc)
  end

  def feed
    @entries = Planet::Models::Entry.order(:published_at => :desc).limit 25
    respond_to do |format|
      format.atom { headers["Content-Type"] = 'application/atom+xml; charset=utf-8'}
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def page_title title, suffix = t(:title)
    if title.blank? || title =~ /home/i
      suffix
    else
      "#{title} - #{suffix}"
    end
  end

  def markdownify text
    Redcarpet::Markdown.new(Redcarpet::Render::HTML, :autolink => true).render(text).html_safe
  end
end

app/helpers/contributors_helper.rb
module ContributorsHelper
  def contributor_type(type)
    case type
    when 'hacker'
      'Hackers'
    when 'painter'
      'Painters'
    when 'community'
      'Community Members'
    else
      'Other'
    end
  end

  def contributor_type_description(type)
    case type
    when 'hacker'
      "Coders, hackers, programmers;  whatever you call them, they are the people who make Diaspora*, fast, reliable and secure."
    when 'painter'
      "They make Diaspora* beautiful."
    when 'community'
      "The people are responsible for the friendly face of Diaspora*"
    else
      'Because they are awesome'
    end
  end
end

app/helpers/i18n_helper.rb
module I18nHelper
  def locale_switcher_entries
    AVAILABLE_LOCALES.map { |key, name|
      locale_switcher_entry key, name
    }.join("\n").html_safe
  end

  def locale_switcher_entry key, name
    content_tag(:li, class: current_locale == key ? 'current' : nil) do
      link_to name, switch_locale_path(locale: key)
    end
  end
end

app/views/blog/index.html.erb
<%- content_for :page_title do %>
  <%= t 'pages.blog.menu_title' %>
<% end %>

<div class="hero" id="masthead">
  <div class="container">
    <h1><%= t 'pages.blog.headline' %></h1>
    <h2 class="lead"><%= t 'pages.blog.subline' %></h2>
  </div>
</div>

<div class="container">
  <%- @blogposts.each_with_index do |blogpost,index| %>
    <div class="row">
      <div class="col-md-12 blogcontent bloglist-item">
        <div class="page-header clearfix <%- if index != 0 %>headline-only<%- end %>">
          <h1><%= link_to blogpost.title, blog_url(blogpost, subdomain: 'blog') %> <small><%= l blogpost.created_at, format: :blog_headline %></small></h1>
        </div>

        <%- if index == 0 %>
          <%= markdownify blogpost.content %>
        <%- end %>
      </div>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= page_title yield :page_title %></title>

  <meta charset="utf-8">
  <%= favicon_link_tag 'favicon.png' %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <%= auto_discovery_link_tag :atom, news_feed_url(subdomain: 'blog'), {:title => t('newsfeed')} %>
  <%= auto_discovery_link_tag :atom, planet_feed_url(subdomain: 'planet'), {:title => t('planet_feed')} %>
  <%= stylesheet_link_tag 'application', :media => 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <%= link_to root_url(subdomain: false), class: 'navbar-brand' do %>
          <%= image_tag 'logo.png', height: 30, alt: t('title'), title: t('title'), id: 'header-logo' %>
        <% end %>
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#mainmenu">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
      <ul class="nav navbar-nav navbar-right collapse navbar-collapse" id="mainmenu">
        <li><%= link_to t('pages.get_involved.menu_title'), get_involved_url(subdomain: false) %></li>
        <li><%= link_to t('pages.blog.menu_title'), blog_index_url(subdomain: 'blog') %></li>
        <li><%= link_to t('.wiki'), 'https://wiki.diasporafoundation.org' %></li>
        <li><%= link_to t('pages.tutorials.menu_title'), tutorials_url(subdomain: false) %></li>
        <li><%= link_to t('.discourse'), 'https://discourse.diasporafoundation.org/' %></li>
        <li>
          <p class="navbar-btn">
            <%= link_to t('buttons.host_pod'), about_url(subdomain: false, anchor: 'host'), class: 'btn btn-primary' %>
            <%= link_to t('buttons.join_diaspora'), root_url(subdomain: false, anchor: 'get_started'), class: 'btn btn-success' %>
          </p>
        </li>
      </ul>
    </div>
  </nav>

  <div id="main-container" class="container-fluid <%= yield :wrapper_class %>">
    <%= yield %>
  </div>

  <footer>
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h4>
            <%= t '.useful_resources' %>
          </h4>
        </div>
      </div>
      <div class="row">
        <div class="col-md-3">
          <ul>
            <li>
              <a href="https://github.com/diaspora/">
                <%= t '.codebase' %>
              </a>
            </li>
            <li>
              <a href="https://wiki.diasporafoundation.org/">
                <%= t '.documentation' %>
              </a>
            </li>
          </ul>
        </div>
        <div class="col-md-3">
          <ul>
            <li>
              <a href="https://github.com/diaspora/diaspora/issues">
                <%= t '.report_bugs' %>
              </a>
            </li>
            <li>
              <a href="https://discourse.diasporafoundation.org/">
                <%= t '.discussion_general' %>
              </a>
            </li>
          </ul>
        </div>
        <div class="col-md-3">
          <ul>
            <li>
              <a href="https://web.libera.chat/?channel=#diaspora">
                <%= t '.irc' %>
              </a>
            </li>
          </ul>
        </div>
        <div class="col-md-3">
          <div class="dropdown dropup">
            <button class="btn btn-defalt dropdown-toggle" data-toggle="dropdown">
              <%= t '.choose_language' %>
              <span class="caret"></span>
            </button>

            <ul class="dropdown-menu">
              <%= locale_switcher_entries %>
              <li>
                <a href="https://wiki.diasporafoundation.org/Contribute_translations">
                  <%= t '.translate' %>
                </a>
              </li>
            </ul>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <p class="license-text">
            <a rel="license" href="https://creativecommons.org/licenses/by/3.0/">
              <%= image_tag 'cc_by.png', alt: t('.cc_license_alt') %>
            </a>
            <%= t('.licensed_under', site_link: '
              <a href="https://diasporafoundation.org/" property="cc:attributionName"
                 rel="cc:attributionURL">
                diasporafoundation.org
              </a>', license_link: %Q{
              <a rel="license" href="https://creativecommons.org/licenses/by/3.0/">
                  #{t('.license_link_text')}
              </a>}).html_safe %>
            </p>
        </div>
      </div>
    </div>
  </footer>
</body>
</html>

app/views/pages/getting_started1.html.erb
<% content_for :page_title, t('.menu_title') %>
<% content_for :wrapper_class, 'index-page' %>

<div id="masthead" class="hero">
  <div class="container">
    <h1><%= t 'pages.tutorials.started_head' %></h1>
    <h2 class="lead"><%= t '.byline' %></h2>
  </div>
</div>

<div class="container">
  <div class="row minor-top-spacing">
    <div class="col-md-12">
      <p class="more-info"><%= t '.welcome' %></p>
      
      <h3><%= t '.find_pod' %></h3>
      <p class="more-info"><%= t('.find_pod_intro', part_link: link_to(t('pages.tutorials.part2'), interface_path)).html_safe %></p>
      <p><%= t('.find_pod_ex1').html_safe %></p>
      <p class="more-info"><%= t('.find_pod_ex2').html_safe %></p>
      <p><%= t('.find_pod_ex3', wiki_link: link_to(t('.wiki_link_text'), "https://wiki.diasporafoundation.org/Choosing_a_pod")).html_safe %></p>
      <p><%= t '.find_pod_ex4' %></p>
      <p class="more-info"><%= t '.find_pod_ex5' %></p>

      <h3><%= t '.registration' %></h3>
      <p><%= t('.registration1').html_safe %></p>
      <p><%= t '.registration2' %></p>

      <p class="text-center"><%= image_tag 'pages/getting_started/sign_up/signup.png' %></p>

      <p><%= t('.registration3').html_safe %></p>
      <p class="more-info">
        <%= t('.registration4',
              dhq_link: link_to(t('.dhq_link_text'), 'https://dia.so/diasporahq'),
              part_link: link_to(t('pages.tutorials.part4'), connecting_path)
        ).html_safe %>
      </p>

      <p><%= t '.registration5' %></p>

      <p class="text-center"><%= image_tag 'pages/getting_started/sign_up/gettingstarted.png' %></p>

      <ol>
        <li><%= t('.registration6').html_safe %></li>
        <li><%= t('.registration7').html_safe %></li>
        <li><%= t('.registration8').html_safe %></li>
        <li><%= t('.registration9').html_safe %></li>
      </ol>

      <p><%= t('.profile1').html_safe %></p>
      <p><%= t('.profile2').html_safe %></p>

      <div class="row">
        <div class="col-md-6">
          <p class="text-center"><%= image_tag 'pages/getting_started/sign_up/profile-basic.png', class: 'img-responsive' %></p>
        </div>
        <div class="col-md-6">
          <p class="text-center"><%= image_tag 'pages/getting_started/sign_up/profile-extended.png', class: 'img-responsive' %></p>
        </div>
      </div>

      <p><%= t('.profile3', part_link: link_to(t('pages.tutorials.part7'), finishing_path)).html_safe %></p>
      <p><%= t('.profile4').html_safe %></p>

      <h3><%= t '.finish' %></h3>
      <p><%= t('.finish_ex1').html_safe %></p>
      <p class="more-info"><%= t('.finish_ex2', part_link: link_to(t('pages.tutorials.part5'), sharing_path)).html_safe  %></p>

      <p class="text-center minor-top-spacing"><%= link_to t('pages.getting_started2.byline'), interface_url %></p>
    </div>
  </div>
</div>

app/views/pages/getting_started2.html.erb
<% content_for :page_title, t('.menu_title') %>
<% content_for :wrapper_class, 'index-page' %>

<div id="masthead" class="hero">
  <div class="container">
    <h1><%= t 'pages.tutorials.started_head' %></h1>
    <h2 class="lead"><%= t '.byline' %></h2>
  </div>
</div>
<div class="container">
  <div class="row top_spacing">
    <div class="span2">&nbsp;
    </div>
    <div class="span12">       
        <h4 class="more-info"><%= t('.interface_mobile', mobile_link: link_to(t('.click_here_text'), interface_mobile_path)).html_safe %></h4>
        <p>&nbsp;</p>
        <p><%= t('.interface1').html_safe %></p>
        <p class="more-info"><%= t '.interface2' %></p>
        
        <p><%= t '.header' %></p>
        <div align="center"><%= image_tag 'pages/getting_started/interface/dropdown.png', class: 'img-responsive' %></div>
        <ol>
          <li><%= t('.header_podname').html_safe %></li>
          <li><%= t('.header_stream').html_safe %></li>
          <li><%= t('.header_notify', part_link: link_to(t('pages.tutorials.part6'), conversations_path)).html_safe %></li>
          <li><%= t('.header_conversations', part_link: link_to(t('pages.tutorials.part6'), conversations_path)).html_safe %></li>
          <li><%= t('.header_search', part_link: link_to(t('pages.tutorials.part4'), connecting_path)).html_safe %></li>
          <li><%= t('.header_dropdown').html_safe %>
            <ul>
              <li><%= t('.header_profile').html_safe %></li>
              <li><%= t('.header_contacts', part_link: link_to(t('pages.tutorials.part4'), connecting_path)).html_safe %></li>
              <li><%= t('.header_settings', part_link: link_to(t('pages.tutorials.part7'), finishing_path)).html_safe %></li>
              <li><%= t('.header_help').html_safe %></li>
              <li><%= t('.header_logout').html_safe %></li> 
            </ul>
          </li>
        </ol>
        
        <p><%= t '.columns' %></p>
        <div align="center"><%= image_tag 'pages/getting_started/interface/stream.jpg', class: 'img-responsive' %></div>
        <p>&nbsp;</p>
            <ul>
                <li><%= t('.column1').html_safe %></li>
                <li><%=(t '.column2', part_link: link_to(t('pages.tutorials.part5'), sharing_path)).html_safe %></li>
            </ul>
        
        <p><%= t '.views' %></p>
        
        <h4><%= t '.stream' %></h4>
        <p><%= t '.stream_ex1' %></p>
            <ol>
                <li><%= t('.stream_contents1').html_safe %></li>
                <li><%= t('.stream_contents2').html_safe %></li>
                <li><%= t('.stream_contents3').html_safe %></li>
                <li><%= t('.stream_contents4', part_link: link_to(t('pages.tutorials.part7'), finishing_path)).html_safe %></li>
            </ol>
        <p><%= t '.stream_ex2' %></p>

        <h4><%= t '.activity' %></h4>
        <p><%= t('.activity_ex').html_safe %></p>
        <p><%= t('.activity_ex2').html_safe %></p>

        <h4><%= t '.mentions' %></h4>
        <p><%= t('.mentions_ex', part_link: link_to(t('pages.tutorials.part5'), sharing_path)).html_safe %></p>

        <h4><%= t '.aspects' %></h4>
        <p><%= t('.aspects_ex1').html_safe %></p>
        <p><%= t('.aspects_ex2').html_safe %></p>

        <h4><%= t '.tags' %></h4>
        <p><%= t('.tags_ex1', part_link: link_to(t('pages.tutorials.part5'), sharing_path)).html_safe %></p>
        <p><%= t('.tags_ex2').html_safe %></p>

        <h4><%= t '.public' %></h4>
        <p><%= t('.public_ex').html_safe %></p>
        
        <h3><%= t '.other_views' %></h3>
        <p><%= t('.other_views_ex').html_safe %></p>
        
        <h4><%= t '.tag_stream' %></h4>
        <p><%= t('.tag_stream_ex').html_safe %></p>
        
        <h4><%= t '.spv' %></h4>
        <p><%= t('.spv_ex').html_safe %></p>
        
        <h4><%= t '.profile' %></h4>
        <p><%= t('.profile_ex1').html_safe %></p>
        <p><%= t('.profile_ex2').html_safe %></p>
        <p><%= t('.profile_ex3', part_link: link_to(t('pages.tutorials.part1'), sign_up_path)).html_safe %></p>
        <p><%= t('.profile_ex4').html_safe %></p>
        <ul>
          <li><%= t('.profile_ex5').html_safe %></li>
          <li><%= t('.profile_ex6').html_safe %></li>
          <li><%= t('.profile_ex7').html_safe %></li>
        </ul>
        <p><%= t('.profile_ex8').html_safe %></p>
        
        <h4><%= t '.themes' %></h4>
        <p><%= t('.themes_ex1', part_link: link_to(t('pages.tutorials.part7'), finishing_path)).html_safe %></p>
        <ul>
          <li><%= t('.themes_list1').html_safe %></li>
          <li><%= t('.themes_list2').html_safe %></li>
          <li><%= t('.themes_list3').html_safe %></li>
          <li><%= t('.themes_list4').html_safe %></li>
          <li><%= t('.themes_list5').html_safe %></li>
          <li><%= t('.themes_list6').html_safe %></li>
        </ul>
        <p><%= t('.themes_ex2').html_safe %></p>
        
        <p>&nbsp;</p>
        <p class="more-info"><%= t('.finish').html_safe %></p>
        
        <p>&nbsp;</p>
 
        <p align="center"><%= link_to t('pages.getting_started1.byline'), sign_up_url %> | <%= link_to t('pages.getting_started3.byline'), aspects_url %></div>
    <div class="span2">
    </div>
  </div>
</div>

app/views/pages/getting_started7.html.erb
<% content_for :page_title, t('.menu_title') %>
<% content_for :wrapper_class, 'index-page' %>

<div id="masthead" class="hero">
  <div class="container">
    <h1><%= t 'pages.tutorials.started_head' %></h1>
    <h2 class="lead"><%= t '.byline' %></h2>
  </div>
</div>

<div class="container">
  <div class="row top-spacing">
    <div class="col-md-12">
      <p class="more-info"><%= t '.intro' %></p>

      <h3><%= t '.connect' %></h3>
      <p><%= t '.connect_ex1' %></p>
      <p class="more-info"><%= t '.connect_ex2' %></p>
      <p><%= t('.connect_ex3').html_safe %></p>
      <p><%= t('.connect_ex4', part_link: link_to(t('pages.tutorials.part5'), sharing_path)).html_safe %></p>

      <h3><%= t '.settings' %></h3>
      <p><%= t('.settings_ex1').html_safe %></p>
      <p><%= t('.settings_ex2').html_safe %></p>

      <h4><%= t '.profile' %></h4>
      <p><%= t('.profile_ex1', part_link: link_to(t('pages.tutorials.part1'), sign_up_path)).html_safe %></p>
      
      <h5><%= t '.nsfw' %></h5>
      <p><%= t('.profile_ex2').html_safe %></p>
      <p><%= t('.profile_ex3').html_safe %></p>

      <h4><%= t '.account' %></h4>
      <p><%= t '.account_ex1' %></p>
      <p class="more-info"><%= t '.account_ex1a' %></p>
      <p><%= t '.account_ex2' %></p>
      <h5><%= t '.spotlight' %></h5>
      <p><%= t '.spotlight_ex' %></p>

      <h4><%= t '.privacy' %></h4>
      <p><%= t('.privacy_ex', part_link: link_to(t('pages.tutorials.part5'), sharing_path)).html_safe %></p>

      <h4><%= t '.services' %></h4>
      <p><%= t('.services_ex', part_link: link_to(t('pages.tutorials.part6'), conversations_path)).html_safe %></p>
      
      <h4><%= t '.applications' %></h4>
      <p><%= t '.applications_ex' %></p>
      
      <p>&nbsp;</p>
      <p><%= t('.finish1').html_safe %></p>
      <p><%= t('.finish2').html_safe %></p>

      <p class="text-center minor-top-spacing"><%= link_to t('pages.getting_started6.byline'), conversations_url %> | <%= link_to t('pages.tutorials.headline'), tutorials_url %></p>
    </div>
  </div>
</div>

app/views/pages/other_docs.html.erb
<% content_for :page_title, t('.menu_title') %>
<% content_for :wrapper_class, 'index-page' %>

<div id="masthead" class="hero">
  <div class="container">
    <h1><%= t '.headline' %></h1>
    <h2 class="lead"><%= t '.byline' %></h2>
  </div>
</div>

<div class="container">
  <div class="row minor-top-spacing">
    <div class="col-md-12">
      <p><%= t '.intro1' %></p>
      <p><%= t '.intro2' %></p>

      <h3><%= t '.tutorials' %></h3>
      <ul>
        <li><a href="http://fr.wikibooks.org/wiki/diaspora_:_Le_guide_du_parfait_d%C3%A9butant" target="_blank">diaspora* : Le guide du parfait débutant</a> – <%= t '.parfait' %></li>
      </ul>

      <h3><%= t '.about' %></h3>
      <ul>
        <li><%= t '.about1' %></li>
        <li><%= t('.wiki', wiki_link: link_to(t('.wiki_link_text'), 'https://wiki.diasporafoundation.org/')).html_safe %></li>
        <li><%= t('.wikipedia', wikipedia_link: link_to('diaspora*', 'http://en.wikipedia.org/wiki/Diaspora_%28social_network%29'), wikipedia_software_link: link_to(t('.wikipedia_software_link_text'), 'http://en.wikipedia.org/wiki/Diaspora_%28software%29')).html_safe %></li>
      </ul>

      <h3><%= t '.support' %></h3>
      <ul>
        <li><%= t('.question').html_safe %></li>
        <li><%= t('.mail', mail_link: link_to(t('.mail_link_text'), 'http://groups.google.com/group/diaspora-discuss')).html_safe %></li>
        <li><%= t('.irc', irc_link: link_to(t('.irc_link_text'), 'https://web.libera.chat/?channel=#diaspora')).html_safe %></li>
      </ul>

      <h3><%= t '.progress' %></h3>
      <ul>
        <li><%= t('.blog', blog_link: link_to(t('.blog_link_text'), 'http://blog.diasporafoundation.org/')).html_safe %></li>
        <li><%= t('.changelog', changelog_link: link_to(t('.changelog_link_text'), 'https://github.com/diaspora/diaspora/blob/develop/Changelog.md')).html_safe %></li>
        <li><a href="https://discourse.diasporafoundation.org/" target="_blank">Discourse</a> – <%= t '.discourse' %></li>
      </ul>

      <h3><%= t '.communication' %></h3>
      <ul>
        <li><%= t('.communicate', communicate_link: link_to(t('.communicate_link_text'), 'https://wiki.diasporafoundation.org/How_we_communicate')).html_safe %></li>
      </ul>

      <h3><%= t '.other' %></h3>
      <ul>
        <li><%= t('.manifesto', manifesto_link: link_to(t('.manifesto_link_text'), 'http://userdatamanifesto.org/')).html_safe %></li>
      </ul>

      <p class="text-center minor-top-spacing"><%= link_to t('pages.tutorials.headline'), tutorials_url %> | <%= link_to t('pages.tutorials.started_head'), sign_up_url %></p>
    </div>
  </div>
</div>

app/views/planet/index.html.erb
<%- content_for :page_title do %>
  <%= t 'pages.planet.menu_title' %>
<% end %>
<% content_for :wrapper_class, 'planet-page' %>

<div class="hero" id="masthead">
  <div class="container">
    <h1><%= t 'pages.planet.headline' %></h1>
    <h2 class="lead"><%= t 'pages.planet.subline' %></h2>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-md-9">
      <%- @entries.each do |entry| %>
        <div class="blogcontent bloglist-item planet-item">
          <div class="page-header clearfix">
            <h1>
              <%= entry.feed.title %>: <%= link_to entry.title, entry.url %>
              <small><%= l entry.published_at, format: :blog_headline %></small>
            </h1>
          </div>

          <%= entry.sanitized_body.html_safe %>
        </div>
      <% end %>
      <div class="text-center">
        <%= will_paginate @entries, renderer: BootstrapPagination::Rails %>
      </div>
    </div>
    <div class="col-md-3">
      <h4><%= t 'pages.planet.disclaimer_headline' %></h4>
      <p class="text-muted"><%= t 'pages.planet.disclaimer' %></p>

      <h4><%= t 'pages.planet.subscribe_headline' %></h4>
      <p class="text-muted"><%= t('pages.planet.subscribe', feed_link: link_to(t('pages.planet.feed_link_title'), planet_feed_path)).html_safe %></p>

      <h4><%= t 'pages.planet.subscriptions_headline' %></h4>
      <ul>
        <%- @subscriptions.each do |subscription| %>
          <li>
            <%= link_to subscription.title, subscription.site_url %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>